Repository Proyecto-integrador-ISPC-2024/proyecto-integrador-web-pp-2025, pull requests merged in 2025-06, with the labels that each got.

#139 Denisse sabeff
  frontend/src/app/components/carousel/carousel.component.html
  frontend/src/app/layout/footer/footer.component.html
  frontend/src/app/layout/header/header.component.html
  frontend/src/styles.css
Labels: bug

#140 agrego cambios de modo oscuro a panel administrador
  frontend/src/styles.css
Labels: bug

#145 Se implementa alert dialog para cancelar pedidos
  frontend/src/app/components/admin-management/admin-management.component.ts
  frontend/src/app/components/order-management/order-management.component.ts
Labels: bug, documentation, enhancement

#152 actualizo mp
  Backend/Tienda_Campeones/.env
  Backend/Tienda_Campeones/web/views/pedidoViews.py
  frontend/src/app/components/cart-resume/cart-resume.component.html
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/interfaces/cartOrder.ts
  frontend/src/app/interfaces/mercadopago.ts
  frontend/src/app/services/api.service.ts
  frontend/src/index.html
Labels: enhancement

#157 Development
  frontend/src/app/components/admin-list-users/admin-list-users.component.html
  frontend/src/app/components/admin-list-users/admin-list-users.component.ts
  frontend/src/app/components/admin-management/admin-management.component.html
  frontend/src/app/components/admin-management/admin-management.component.ts
  frontend/src/app/components/admin-orders-summary/admin-orders-summary.component.html
  frontend/src/app/components/admin-orders-summary/admin-orders-summary.component.ts
  frontend/src/app/components/cart-resume/cart-resume.component.html
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/components/order-management/order-management.component.html
  frontend/src/app/components/order-management/order-management.component.ts
  frontend/src/app/components/orders-summary/orders-summary.component.html
  frontend/src/app/components/orders-summary/orders-summary.component.ts
  frontend/src/app/pages/admin-dashboard/admin-dashboard.component.html
  frontend/src/app/pages/admin-dashboard/admin-dashboard.component.ts
  frontend/src/app/pages/client-dashboard/client-dashboard.component.html
  frontend/src/app/pages/client-dashboard/client-dashboard.component.ts
  frontend/src/app/services/orders.service.ts
Labels: documentation, enhancement
