Repository Proyecto-integrador-ISPC-2024/proyecto-integrador-web-pp-2025, pull requests merged in 2025-05, with the labels that each got.

#41 Victoria urcola
  .gitignore
  Backend/Tienda_Campeones/Tienda_Campeones/settings.py
  Backend/Tienda_Campeones/Tienda_Campeones/urls.py
  Backend/Tienda_Campeones/users/views.py
  frontend/src/app/components/contact-form/contact-form.component.ts
  frontend/subnano-error_de_version.txt
  requirements.txt
Labels: enhancement

#52 feat: implementar sistema de login/logout con cambio dinámico de íconos
  frontend/src/app/components/login-form/login-form.component.html
  frontend/src/app/components/login-form/login-form.component.ts
  frontend/src/app/components/logout-modal/logout-modal.component.ts
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/layout/header/header.component.ts
  frontend/src/app/services/auth-interceptor.interceptor.ts
  frontend/src/app/services/auth.service.ts
Labels: documentation, enhancement

#53 Denisse sabeff - terminos y condiciones
  Backend/Tienda_Campeones/Tienda_Campeones/settings.py
  frontend/package-lock.json
  frontend/src/app/app.routes.ts
  frontend/src/app/layout/footer/footer.component.html
  frontend/src/app/pages/terminos-condiciones/terminos-condiciones.component.css
  frontend/src/app/pages/terminos-condiciones/terminos-condiciones.component.html
  frontend/src/app/pages/terminos-condiciones/terminos-condiciones.component.spec.ts
  frontend/src/app/pages/terminos-condiciones/terminos-condiciones.component.ts
Labels: documentation, enhancement

#59 Valentina tachini
  frontend/src/app/app.component.ts
  frontend/src/app/app.routes.ts
  frontend/src/app/components/login-form/login-form.component.html
  frontend/src/app/components/register-form/register-form.component.html
  frontend/src/app/components/register-form/register-form.component.ts
  frontend/src/styles.css
Labels: documentation, enhancement

#60 reemplazo de alert por toastr en los formularios y componentes de log…
  frontend/src/app/components/card-product/card-product.component.ts
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/components/contact-form/contact-form.component.ts
  frontend/src/app/components/login-form/login-form.component.ts
  frontend/src/app/components/register-form/register-form.component.ts
  frontend/src/app/guards/auth.guard.ts
  frontend/src/app/pages/cart/cart.component.ts
  package-lock.json
  package.json
Labels: documentation, enhancement

#61 Se crea el componente dark-theme
  frontend/src/app/dark-theme/dark-theme.component.css
  frontend/src/app/dark-theme/dark-theme.component.html
  frontend/src/app/dark-theme/dark-theme.component.spec.ts
  frontend/src/app/dark-theme/dark-theme.component.ts
  frontend/src/app/layout/header/header.component.ts
  frontend/src/styles.css
Labels: documentation, enhancement

#63 Mejora UX: animacion en la navegacion superior al hacer hover #WEB#US13#TK1
  frontend/src/app/layout/header/header.component.css
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/layout/header/header.component.ts
Labels: documentation, enhancement

#71 Lautaro pena
  Backend/Tienda_Campeones/users/usuarioapi/usuario_serializers.py
  frontend/src/app/app.routes.ts
  frontend/src/app/components/admin-list-users/admin-list-users.component.css
  frontend/src/app/components/admin-list-users/admin-list-users.component.html
  frontend/src/app/components/admin-list-users/admin-list-users.component.ts
  frontend/src/app/pages/admin-dashboard/admin-dashboard.component.css
  frontend/src/app/pages/admin-dashboard/admin-dashboard.component.html
  frontend/src/app/pages/admin-dashboard/admin-dashboard.component.ts
  frontend/src/app/services/admin.service.ts
  frontend/src/app/services/users.service.ts
Labels: documentation, enhancement

#73 Denisse sabeff
  frontend/src/app/pages/terminos-condiciones/terminos-condiciones.component.html
Labels: bug

#74 Agrego ruta para terminos y condiciones
  frontend/src/app/app.routes.ts
Labels: bug

#75 Lautaro pena
  frontend/src/app/app.routes.ts
Labels: documentation, enhancement

#76 Se implementó la calculadora de ventas, su servicio y se mejoró el da…
  Backend/Tienda_Campeones/web/views/pedidoViews.py
  frontend/src/app/components/sales-calculator/sales-calculator.component.css
  frontend/src/app/components/sales-calculator/sales-calculator.component.html
  frontend/src/app/components/sales-calculator/sales-calculator.component.ts
  frontend/src/app/pages/admin-dashboard/admin-dashboard.component.html
  frontend/src/app/pages/admin-dashboard/admin-dashboard.component.ts
  frontend/src/app/services/admin.service.ts
  frontend/src/app/services/sales.service.ts
Labels: documentation, enhancement

#78 Denisse sabeff
  frontend/src/app/components/cart-list/cart-list.component.ts
  frontend/src/app/pages/landing/landing.component.css
  frontend/src/app/pages/landing/landing.component.html
  frontend/src/app/pages/terminos-condiciones/terminos-condiciones.component.html
  frontend/src/app/services/cart.service.ts
Labels: bug, enhancement

#80 fix de ruta de unauthorized
  frontend/src/app/app.routes.ts
Labels: bug

#82 reparacion de links
  frontend/src/app/pages/products/products.component.html
Labels: bug

#84 Corrección de errores en varios componentes y servicios
  Backend/Tienda_Campeones/users/usuarioapi/UsuarioView.py
  Backend/Tienda_Campeones/users/usuarioapi/usuario_serializers.py
  frontend/src/app/app.routes.ts
  frontend/src/app/components/admin-list-users/admin-list-users.component.html
  frontend/src/app/components/admin-list-users/admin-list-users.component.ts
  frontend/src/app/components/admin-management/admin-management.component.ts
  frontend/src/app/components/card-product/card-product.component.html
  frontend/src/app/components/card-product/card-product.component.ts
  frontend/src/app/components/carousel/carousel.component.html
  frontend/src/app/components/carousel/carousel.component.ts
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/components/logout-modal/logout-modal.component.ts
  frontend/src/app/components/order-management/order-management.component.ts
  frontend/src/app/guards/client.guard.ts
  frontend/src/app/interfaces/sales.ts
  frontend/src/app/layout/footer/footer.component.html
  frontend/src/app/layout/footer/footer.component.ts
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/layout/header/header.component.ts
  frontend/src/app/pages/cart/cart.component.ts
  frontend/src/app/pages/client-dashboard/client-dashboard.component.ts
  frontend/src/app/pages/dashboard/dashboard.component.ts
  frontend/src/app/services/admin.service.ts
  frontend/src/app/services/auth-interceptor.interceptor.ts
  frontend/src/app/services/auth.service.ts
  frontend/src/app/services/orders.service.ts
  frontend/src/app/services/sales.service.ts
  frontend/src/app/services/users.service.ts
Labels: bug, documentation, enhancement
